---
title: | 
	| Gunshots and Turf Wars
	| \tiny \hfill
    | \Large Inferring Gang Territories from Administrative Data
author: 
	- name: Brendan Cooley
      affiliation: Ph.D. Candidate, Department of Politics, Princeton University
    - name: Noam Reich
      affiliation: Ph.D. Candidate, Department of Politics, Princeton University
date: \today
abstract: Street gangs are conjectured to engage in violent territorial competition. This competition can be difficult to study empirically as the number of gangs and the division of territory between them are usually unobserved to the analyst. However, traces of gang conflict manifest themselves in police and administrative data on violent crime. In this paper, we show that the frequency and location of shootings are sufficient statistics for the territorial partition under mild assumptions about the data generating processes for gang-related and non-gang related shootings. We then show how to estimate this territorial partition from a panel of geolocated shooting data. We apply our method to analyze the structure of gang territorial competition in Chicago using victim-based crime reports from the Chicago Police Department. The method reveals both the number of gangs in operation in Chicago and their territorial boundaries.
thanks: Thanks go here.
# jelcodes: JEL codes go here

bibliography: /Users/bcooley/Dropbox (Princeton)/References/library.bib
biblio-style: apsr

papersize: letter
documentclass: article
geometry: margin=1.25in
link-citations: true

output:
	fig_caption: yes
    citation_package: natbib

---

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

helperPath <- "source/R/"
helperFiles <- list.files(helperPath)
for (i in helperFiles) {
  source(paste0(helperPath, i))
}

libs <- c()
ipak(libs)

# not available
Aintragang_nz <- "NA"
Aintragang_iid <- "NA"
Aintergang_symmetry <- "NA"
Aintergang_iid <- "NA"

Pcov <- "NA"

Ccov <- "NA"

Apdx_cov <- "NA"

if (file.exists('references.RData')) load('references.RData')

# setup definition, assumption, proposition, lemma tickers
Atick <- 1
Ptick <- 1
Ctick <- 1

```

\newpage

# Introduction

# Literature

# Data

# Model

```{r, child = "sections/model.rmd"}
```

# Estimation

# Results

# Conclusion


\clearpage


# Appendices

```{r Appendix Numbering, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

a <- 1
Apdx_cov <- LETTERS[a]

```

## Appendix `r Apdx_cov`: Covariance Derivation

```{r, child="sections/Apdx_cov.rmd"}
```

\clearpage

# References

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

save.image('references.RData')

```