```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

source("../01_code/00_params.R")
libs <- c("tidyverse")
ipak(libs)

sample_agreement_ratio <- read_csv(sample_agreement_ratio_path, col_names=FALSE) %>% pull()
cpd_agreement_ratio <- read_csv(cpd_agreement_ratio_path, col_names=FALSE) %>% pull()
cpd_agreement_ratio_ci <- quantile(cpd_agreement_ratio, c(.025, .975))

J_all <- read_csv(J_all_path, col_names=FALSE) %>% pull(.)
K <- J_all - 1
K <- K %>% sort()

K_lower <- K[3]
K_upper <- K[97]

```

Street gangs are conjectured to engage in violent territorial competition. This competition can be difficult to study empirically as the number of gangs and the division of territory between them are usually unobserved to the analyst. However, traces of gang conflict manifest themselves in police and administrative data on violent crime. In this paper, we show that the frequency and location of shootings are sufficient statistics number of gangs in operation and the territorial partition beween them under mild assumptions about the data generating processes for gang-related and non-gang related shootings. We then show how to estimate this territorial partition from a panel of geolocated shooting data. We apply our method to analyze the structure of gang territorial competition in Chicago using victim-based crime reports from the Chicago Police Department (CPD) and validate our methodology on gang territorial maps produced by the CPD. We detect the presence of `r K_lower`-`r K_upper` gangs whose estimated territorial footprints we match to CPD maps. After matching, `r round(cpd_agreement_ratio_ci[1]*100, 0)`-`r round(cpd_agreement_ratio_ci[2]*100, 0)` percent of our partition labels agree with those of the CPD. This performance compares favorably to an agreement rate of `r round(sample_agreement_ratio*100, 0)` percent when CPD labels are randomly permuted.
