```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

source("../01_code/00_params.R")
libs <- c("tidyverse")
ipak(libs)

chi_clean <- read_csv(crimes_clean_path) 
chi_clean2019 <- chi_clean %>% filter(year=="2019-01-01")

chi_hnfs2019 <- nrow(chi_clean2019 %>% filter(hnfs==1)) 

sample_agreement_ratio <- read_csv(sample_agreement_ratio_path, col_names=FALSE) %>% pull()
cpd_agreement_ratio <- read_csv(cpd_agreement_ratio_path, col_names=FALSE) %>% pull()
cpd_agreement_ratio_ci <- quantile(cpd_agreement_ratio, c(.025, .975))

gang_area_means <- read_csv(paste0(gang_territory_path, "gang_area_means.csv"))

gd_vl_bps_area <- gang_area_means %>% filter(gang %in% c("black p stones", "gangster disciples", "vice lords")) %>% pull(area_mean) %>% sum()
all_area <- gang_area_means %>% pull(area_mean) %>% sum()

```

In 2019, `r prettyNum(chi_hnfs2019, big.mark=",", scientific=FALSE)` people were murdered or shot in the city of Chicago. Chicago is far from the most violent American city on a per capita basis — other large municipalities confront alarmingly high rates of interpersonal violence.  Law enforcement agencies and researchers believe much of this violence is connected to street gangs and disputes amongst their members. Between 1994 and 2006, law enforcement officials classified 35-50 percent of Chicago homicides as gang-related [@Papachristos2009; @NDIC2007].^[@Papachristos2009 reports that homicide detectives classified 35 percent of homicides as gang-related in the years 1994, 1998, and 2002. A Department of Justice report claims that 50 percent of Chicago homicides in 2006 were gang-related. According to @Howell2018, these numbers are not unusual -- other large police departments classify between 20 and 50 percent of local homicides as gang-related.] Inter-gang warfare and intra-gang violence feature prominently alongside drug-dealing in many ethnographic accounts of street gangs and their operations [@Sanchez1991; @Decker1996; @Papachristos2009; @Vargas2016]. In one oft-cited case, a gang's monthly costs of protection and aggression —- hiring mercenaries, paying tribute, procuring weapons, and staging funerals —- dwarfed the wholesale costs of all drugs sold by its dealers [@Levitt2000].

Gangs operate over well-defined territories from which they extract rents through racketeering, drug-selling monopolies, and other criminal activity [@Thrasher1927; @Sanchez1991; @Levitt2000; @Venkatesh2000]. Gangs war with one another over control of these rent streams and in response to challenges to their individual or collective reputations [@Brantingham2012; @Papachristos2013; @Ebdm2018]. Anecdotal evidence suggests that such wars are frequent and are a major source of gang-related violence [@Levitt2000]. However, our knowledge of gangs and their territorial footprints remains largely anecdotal because gangs are necessarily covert and opaque organizations. Information on gang activities or territories from law enforcement agencies is generally unavailable either because it is uncollected or because it is not shared with the public.^[The Chicago Police Department's gang maps are the most well-known and are available to researchers thanks to Freedom of Information requests by @Bruhn2019.] Moreover, the data produced by such efforts are subject to well-known biases and unclear methodologies [@Kennedy1996; @Levitt1998; @Carr2016]. **TKTK be explicit about biases** Existing open-source methodologies used to estimate gangs' territorial footprints require deep subject matter expertise that make them difficult to generalize beyond their target locale [@Sobrino2019; @Melnikov2019; @Signoret2020].

In this paper, we propose and implement a method to estimate the number of gangs operating in a given location and their territorial footprints. Our approach requires the analyst observe only the location and timing of all (gang-related and non-gang related) violent events within the area under study —- data that are widely available in administrative records on crime. We apply this method to study gangs in Chicago, a city in which a panel of gang maps produced by the Chicago Police Department (CPD) are publicly available [@Bruhn2019]. We detect the presence of 3 gangs on average, whose estimated territorial footprints correspond roughly to those of the Gangster Disciples, the Black P Stones, and the Vice Lords. While these constitute a small fraction of all gangs operating in Chicago, they are among the largest by membership and territorial extent. Together, these gangs own `r round(gd_vl_bps_area / all_area*100, 1)` percent of all gang turf in the city, according to CPD maps. 

We begin by modeling the data-generating process for violent events. These fall into three categories: inter-gang, intra-gang, and non-gang. Gangs are assigned to territories according to an unobserved partition function. Period-specific shocks induce territorially-circumscribed conflict between and within gangs. Non-gang violence exhibits no spatial correlation. We show that this model generates a distinct pattern of spatial covariance in violent events. We prove that under our model, the spatial covariance in violence is a sufficient statistic for the underlying territorial partition. The model follows closely that of @Trebbi2019. Our innovation is to generalize their approach, used to study terrorist groups in Afghanistan and Pakistan, to a setting featuring bilateral conflict between violent organizations. 

We estimate the model on the observed spatial covariance in homicides and non-fatal shootings across Census tracts in Chicago from `r bruhn_sy`-`r bruhn_ey`. Our data come from victim-based crime reports from the Chicago Police Department. We estimate the number of gangs and the territorial partition in sequence. We estimate the number of gangs by iteratively fitting the model, holding this quantity fixed, until out-of-sample fit ceases to improve. We proceed to estimate the territorial partition using spectral clustering [@Luxberg2007], following @Lei2015. This returns the set of census tracts belonging to each gang, as well as the "peaceful" set of territories in which no gang operates. It also produces estimates for the parameters relating to the intensity of between- and within-group conflict. We quantify our uncertainty surrounding the territorial partition and these parameters through non-parametric bootstrap, sampling the set of homicides and non-fatal shootings with replacement and re-estimating the number of gangs and the territorial partition amongst them. 

We permute our most-likely census tract labels to best-approximate a smoothed (over time) map of gang territories and peaceful tracts produced by the CPD. We then compare our estimated partition to the CPD gang maps. In 95 percent of bootstrap iterations, `r round(cpd_agreement_ratio_ci[1]*100, 1)`-`r round(cpd_agreement_ratio_ci[2]*100, 1)` percent of our census tract labels agree with those of the CPD.^[These agreement ratios are constructed by permuting our labels to most-closely match those of the CPD.] Random permutations of the CPD's labels produce agreement in only `r round(sample_agreement_ratio*100, 1)` percent of cases.

Methodologically, our paper is most closely related to the literature on stochastic block models (SBMs), starting with @Holland1983. These models partition actors (nodes) into communities who interact with one another in a Bernoulli process according to community dyad-specific probabilities. Various methods have been developed for "community detection" -- estimating the underlying communities from observed interactions [@Copic2009; @Jin2015]. Like @Trebbi2019, we replace the binary matrices that describe these interactions with continuous spatial covariance matrices describing the likelihood that shootings occur in a pair of locations during the same period. The model of @Trebbi2019 is akin to a special case of the SBM in which actors only interact (commit acts of violence) with members of their own community. In our model, interactions occur both within and between the underyling communities (gangs in our case). 

We leverage "spectral" estimators developed in the statistics literature to estimate our model [@Luxberg2007; @Jin2015; @Lei2015; @Chen2018]. These estimators exploit the relationship between an eigen-decomposition of the spatial covariance matrix and the underlying parameters. In doing so, they render the estimation problem solvable via k-means clustering. @Lei2015 provide conditions under which these estimators are asymptotically consistent for the parameters of the SBM *in the number of nodes*. We are not aware of any papers studying the properties of these estimators, applied to the covariance matrix, in the number of *periods*. We estimate the number of gangs in operation using the cross-validation approach of @Chen2018, which iteratively estimates model parameters on rectangular subsets of the covariance matrix and predicts held-out covariances under different assumptions about the underlying number of communities.^[Here we also depart from the approach of @Trebbi2019, who employ permutation tests on the geographic proximity of within-community locations to estimate the number of communities. Given the strong non-convexity of gang territory in Chicago [@Bruhn2019], we sought a more flexible approach.]

The paper proceeds as follows. We first briefly review the substantive and methodological literature upon which our paper builds. We then describe the crime data and CPD gang maps, used for estimation and validation, respectively. Section IV introduces our model and derives the spatial covariance structure used for estimation. We develop our estimators for the number of gangs and the territorial partition in Section V. We present our results and validate them on the CPD gang maps in Section VI before concluding. 